### ISSUE TITLE
After encoding the video, the length of the video is missing in the file's properties

### ISSUE THREAD

**Issue by TharNyi13** [fluent-ffmpeg/node-fluent-ffmpeg#1209]
### Version information

* fluent-ffmpeg version: ^2.1.2
* ffmpeg version: -
* OS: Windows 10 Home

I am new to using [node-fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg).
Thanks!

### Code to reproduce

```js
      const currentDirectory = process.cwd();
      const inputFilePath = path.join(currentDirectory, "original-video.mp4");
      const outputFilePath = fs.createWriteStream(
        "E:/test-video/output-video.mp4"
      );

      ffmpeg({ source: inputFilePath })
        .format("mp4")
        .videoCodec("libx264")
        .size("1920x1080")
        .aspectRatio("16:9")
        .outputOptions([
          "-movflags",
          "frag_keyframe+empty_moov+faststart",
          "-preset",
          "veryfast",
          "-crf",
          "23",
        ])
        .pipe(outputFilePath, { end: true });

```

(note: Length of the video is missing!)

![image](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/assets/106720216/3485e17c-8767-4b13-99d2-fc21191d12ef)
original-video is downloaded from YouTube / outupt-video is encoded with [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg).

### Expected results

I want to encode the video with the correct encoding options, similar to those used for YouTube videos, and set the correct duration for the video length after the encoding process is complete.

### Observed results

After encoding a simple video from YouTube, the output video does not have a length or duration.

**Comment by njoyard** [comment]
Do you have the same results when using
This looks like an issue with ffmpeg, not with fluent-ffmpeg. Please ensure first that what you want to achieve works on command line.

You can get the command line that was run by fluent-ffmpeg by adding a `'start'` event handler in your chain:

```js
ffmpeg()
  .on('start', function(commandLine) {
    console.log('Spawned Ffmpeg with command: ' + commandLine)
  })
  ...
```

Run the command line manually, and determine if the same issue happens on command line. Be careful of properly escaping the command line contents for your shell. If your code is using streams, you will have to adapt the command line in order to pass the same inputs to ffmpeg.

- If it does happen as well, your issue is related to ffmpeg itself, there is nothing we can do here to help you. Have a look at the [ffmpeg documentation][http://ffmpeg.org/documentation.html] and ask the [ffmpeg community][http://ffmpeg.org/contact.html].
- Otherwise, this may be a fluent-ffmpeg bug. Please report back here with the results of your tests.
