### ISSUE TITLE
Mapping/copying metadata stream

### ISSUE THREAD

**Issue by scaryguy** [fluent-ffmpeg/node-fluent-ffmpeg#369]
Hi there,

First of all, thank you for this great library. Here is my question:

I have a `.ts` file and all I want is dividing the file into 2 separate files with different durations. ***Everything*** must be the same except their durations. ***Video codec, audio codec and all metadata***...

How do I do this with your library? Are there any shortcuts for this purpose?

I tried following:

```javascript
		var command = ffmpeg(last_segment_path)
			.on('start', function(commandLine) {
				console.log('@@@@@ COMMAND: ' + commandLine);
			})
			.seekInput('0.000')
			.outputOptions(['-c copy'])
			.duration(crop)
			.on('error', function(err, stdout, stderr) {
				console.log('@@@@@ VIDEO COULD NOT BE PROCESSED: ' + err.message);
			})
			.output('output/'+ "_" + config.default_bitrate + "_av-p.ts").run();
```

and 

```javascript
...

.videoCodec('copy')
.audioCodec('copy')
...
```

and
```javascript
...
.outputOptions(['-c copy', '-map_metadata 0:s'])
...
```

Thanks!

**Comment by njoyard** [comment]
Hi and sorry for the delay.

First, I don't think you need to use seekInput at all, since you're seeking to 0. To copy audio and video, you can use `.audioCodec('copy').videoCodec('copy')`. There's no shortcut for map_metadata, so you're left with `.outputOptions('-map_metadata 0:s')`.

What happens when you do that ?

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.
