### ISSUE TITLE
Screenshot quality/compression

### ISSUE THREAD

**Issue by lanceschi** [fluent-ffmpeg/node-fluent-ffmpeg#397]
Hi,

is it possible to set screenshot[s] image quality/compression?

Thanks.

Cheers,
Luca

**Comment by njoyard** [comment]
That's not currently possible. You can do it manually by duplicating and modifying the `screenshots()` method:

```js
var ffmpeg = require('fluent-ffmpeg');
ffmpeg.prototype.myScreenshot = function(config, folder) {
  // copy from lib/recipes.js
}
```

**Comment by lanceschi** [comment]
@njoyard thx for the nice explanation :+1:.

Actually I realized I was in need of a finer tool for image manipulation. I headed towards [GraphicsMagick](http://www.graphicsmagick.org/) and Node [gm](http://aheckmann.github.io/gm/) module. Around additional 100MB, although so far so good :smiley:

**Comment by njoyard** [comment]
Closing this because it has not had any activity for months. Feel free to reopen if you still have issues/questions :)

**Comment by timdp** [comment]
Personally, I'd still really appreciate this feature. Not sure if that warrants a reopen.

**Comment by njoyard** [comment]
It could. But honestly I don't like the way the screenshots feature works (even if I rewrote it for the 2.x release), and how we have to write code for each little feature we need to add to it. Fluent-ffmpeg's goal is to *help you* do this kind of processing, not provide a black box that magically performs complex recipes using ffmpeg.

I'm even thinking of getting rid of it altogether and replacing it with an example (actually that's why it resides in a "recipes" module), but I'd like to avoid breaking compatibility... Maybe add a deprecation warning on first use...

**Comment by timdp** [comment]
Isn't the main issue here that you can't pass arbitrary ffmpeg command line arguments to screenshots()? Or will it accept addOption()? I forget.

It wouldn't be the most elegant API, but if you could already just pass in custom flags for the image filter, that'd help a lot in terms of customizability.

Of course, like you said, there's always going to be a tradeoff between invoking ffmpeg yourself and dealing with command line arguments, streams, etc. to leverage its full feature set, and using fluent-ffmpeg to get a human-readable, easy-to-use API. It's just that right now, the screenshot feature doesn't really deliver either of those.

**Comment by timdp** [comment]
For what it's worth, my code uses fluent-ffmpeg to produce PNGs, which I then convert to JPEG using GraphicsMagick. Other parts of my app rely on GraphicsMagick anyway, so it's not a huge deal, but it's still an unnecessary step that is basically introduced by fluent-ffmpeg's inability to configure the JPEG encoding. Not to complain, it's just the real-life scenario in my particular case.
