### ISSUE TITLE
Merge is failing [ ffmpeg exited with code 1]

### ISSUE THREAD

**Issue by ngomezleal** [fluent-ffmpeg/node-fluent-ffmpeg#424]
Hi I need help.
This is my code:
var videoFile1 = path.join(__dirname, 'uploads', '1_empresaspolar.webm'),
audioFile2 = path.join(__dirname, 'uploads', '2_empresaspolar.wav');
var mergedFilevideo2 = path.join(__dirname, 'uploads', 'demo-merged.webm');
var ffmpeg = require('fluent-ffmpeg');
console.log(videoFile1);
console.log(audioFile2);
var proc = new ffmpeg({ source: videoFile1 })
.mergeAdd(audioFile2)
.mergeToFile(mergedFilevideo2);

But, I show the follow error:

C:\xampp\htdocs\MediaStreamRecorder\demos>node server
Stop-MAKING MERGE
C:\xampp\htdocs\MediaStreamRecorder\demos\uploads\1_empresaspolar.webm
C:\xampp\htdocs\MediaStreamRecorder\demos\uploads\2_empresaspolar.wav
events.js:85
throw er; // Unhandled 'error' event
^
Error: ffmpeg exited with code 1
at ChildProcess. (C:\xampp\htdocs\MediaStreamRecorder\node_module
s\fluent-ffmpeg\lib\processor.js:735:20)
at ChildProcess.emit (events.js:110:17)
at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

Please helpme.
Regards,

Nelson
Vzla

**Comment by njoyard** [comment]
Hi,

Please read the contribution guide (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/CONTRIBUTING.md) on how to report errors correctly.

You should always have a 'error' handler on the command. Additionally, I think your problem comes from the fact that you're trying to merge audio and video tracks. That's not what the `mergeToFile` method is for, despite its name (see the documentation).

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.
