### ISSUE TITLE
Capture ffmpeg stdout

### ISSUE THREAD

**Issue by mon1020** [fluent-ffmpeg/node-fluent-ffmpeg#469]
Hi,

We want to read the stdout of ffmpeg command in fluent-ffmpeg. For example the fps, time, etc.
What is the event/function to do this?

Thanks in advance!

**Comment by njoyard** [comment]
Ffmpeg stdout and stderr are passed to the 'end' event, in that order.

This is not documented, though, but it will not change due to its usage for debugging and testing purposes.

There's a pending pull request that emits stderr events when ffmpeg emits a line on stderr. Maybe we'll do the same for stdout.

**Comment by mon1020** [comment]
Hi,

Thanks for the reply!
My objective was to get the current FPS, time etc. i could do this using .progress event.
