### ISSUE TITLE
Issue with whitespaces on metadata options

### ISSUE THREAD

**Issue by matheuschimelli** [fluent-ffmpeg/node-fluent-ffmpeg#502]
I think that node-fluent-ffmpeg  have issue with whitespaces on `-metadata` values.
This is my code:
```
.outputOptions([
        '-i',
        __dirname+'/downloads/'+videoName+'.png',
        '-map 0:0',
        '-map 1:0',
        '-c copy',
        '-id3v2_version 3',
        '-metadata artist='+artistName,
        '-metadata title='+trackName,
        '-metadata album='+collectionName,
        '-metadata composer='+artistName,

        
    ])

```
but when i try this, ffmpeg return a error 
```
Unrecognized option 'metadata artist="Alan Walker"'.
Error splitting the argument list: Option not found
```
But if i remove the  variables whitespaces with `.replace(/ /g,'')` it works.

**Comment by njoyard** [comment]
You have to [quote them](https://www.ffmpeg.org/ffmpeg-utils.html#Quoting-and-escaping).

**Comment by matheuschimelli** [comment]
@njoyard you can give me an example?

**Comment by njoyard** [comment]
ffmpeg uses single quotes for quoting so that would be `artist='Alan Walker'`. Additionnally if you want to pass spaces to ffmpeg you cannot use the legacy '-option arg' syntax with fluent-ffmpeg, you have to pass them as separate arguments :

```js
.outputOptions(
  "-map", "0:0",
  "-metadata", "artist='Alan Walker'"
);
```

And finally *don't pass input (-i filename) or codecs (-c copy) to outputOptions* ! Use the fluent-ffmpeg API. There's no point in using fluent-ffmpeg if you're building the command line yourself.

**Comment by matheuschimelli** [comment]
Working :+1:

**Comment by anantakrishna** [comment]
Interestingly, in the latest version (2.1.2) there is no need to quote the metadata values. However, this works only when you pass parameters as values, not as array. Seems it's due to the splitting in this line: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/options/custom.js#L113.

**Comment by rpidburachynskyi** [comment]
> Interestingly, in the latest version (2.1.2) there is no need to quote the metadata values. However, this works only when you pass parameters as values, not as array. Seems it's due to the splitting in this line: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/options/custom.js#L113.

You just saved me a life, thank you. I've spend about 2 hours trying to understand what's wrong, but yeah, passing them as arguments not array works fine.

**Comment by anantakrishna** [comment]
Glad it helped. That's why we share our findings — to build a knowledge base for each other. :pray:
