### ISSUE TITLE
To convert and pipe live images

### ISSUE THREAD

**Issue by pranjalsingi** [fluent-ffmpeg/node-fluent-ffmpeg#591]
Hello,

I want to stream a real time video to a browser. I have a camera API which generates images on the fly. What I want to do is as soon as the camera grabs and saves an image to the directory, I want to take that image, convert it and pipe it. 

In my camera API, I have a buffer of 5 and after the fifth image it again writes to the first image. I have written code for doing something but it doesn't work correctly.
The code is here - 

```
app.get('/video', function(req, res){
	res.contentType('flv');
	var proc = ffmpeg('/root/flycapture.2.9.3.43_armhf/bin/14135894-%d.jpg')
		.format('flv')
		.videoCodec('libx264')
  		.loop()
  		.fps(15)
  		.on('end', function() {
    		console.log('file has been converted succesfully');
  		})
  		.on('error', function(err) {
    			console.log('an error happened: ' + err.message);
  		})
		.pipe(res, {end:true});
});
```

For watching the directory where the image is saved, I do following - 
```
var previousImage = '';
  var imageName = '14135894-0.jpg';

  // Watching the directory bin for changes of file
  fs.watch('bin/', function(event, filename){
    // When the file changes, it will run the if condition
    if (filename != imageName){
      // Change the imageName to filename and emit with help of socket
      previousImage = imageName;
      imageName = filename;
      uploadImage();
    }; 
```
I can call something as I called uploadImage() when a new image is generated. Or anything other that this would also work.
I would really appreciated if you can help in this.

Thanks

**Comment by njoyard** [comment]
Why would you want to convert each image to flv ? Why not just send each image directly to the client and display it ?

**Comment by pranjalsingi** [comment]
I am doing the same thing. My uploadImage function with the help of sockets sends images to client directly. But that is generating soo much of network traffic. The image gets saved in the browser cache and then browser gets it. It happens every 60 ms seconds or soo. And I think this is a bad. 

Also if someone doesn't have a good network speed or is far away, it might get problem.

**Comment by njoyard** [comment]
I don't think ffmpeg has a way of generating a flv dynamically with new files appearing all the time. It will generate a flv with all files present when it started, but will stop then.

The "right" way to have a web client display live video is:
- run ffserver or equivalent, configure it to serve a RTP/RTSP stream
- run ffmpeg with *a real video capture device* (not captured files) as an input and make it output to ffserver
- point the client <video> tag to the rtp/rtsp stream URL

And you don't need nodejs/express for this.

If the only thing you get from the camera is image files, what you could do is generate video by chunks of a certain length (say 5 seconds for example). Every 5 seconds, you run a ffmpeg command to convert all images from the last 5 seconds into flv and send the URL to this flv to your client via a websocket. Of course you will have a 5 second latency in this case. Also you will need to move files around so that you're sure to keep files for 5 seconds.

But you should really look into using a real capture device here. Writing an image on the SD card every 60ms is definitely a bad idea.

**Comment by pranjalsingi** [comment]
Thanks for the suggestions. I am a beginner and still trying to learn stuff but I got what you said in "right" way. This means I can run my node server and ffserver simultaneously on RaspberryPi and have a live stream as well as different things I might require.  But I would like to add in here.

The camera I am using is a Point Grey research grade camera and it has its own GUI which uses some libraries to display the video and has several other sample code to acquire images.  It doesn't expose me to /dev/video0.
Coming to if I have only access to image files, 5 seconds would be a lot of delay. I know its very bad to convert each pixel and then save it at disk because it consumes time as well.
But my professor told me to have a live stream and then if I would like to capture an image, it should let me do that too.

Is there any other suggestion you can give me so that I can work with this set up. 
Someone pointed out to use v4l2loopback to create a fake /dev/video0 , feed in the image there and then use ffmpeg and ffserver. But i don't know how to feed in image through Node to v4l2loopback.
