### ISSUE TITLE
Process ran into a timeout

### ISSUE THREAD

**Issue by dnish** [fluent-ffmpeg/node-fluent-ffmpeg#647]
Hey,
sometimes we get the following error in our logs:

```
--BEGIN FFMPEG ERROR--
Error: process ran into a timeout (600s)
    at Timeout._onTimeout (/var/www/app-files/source/node_modules/fluent-ffmpeg/lib/processor.js:465:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

frame=  762 fps=1.4 q=27.0 size=    3229kB time=00:00:25.86 bitrate=1022.6kbits/s dup=485 drop=0    
frame=  762 fps=1.4 q=27.0 size=    3229kB time=00:00:25.86 bitrate=1022.6kbits/s dup=485 drop=0    
....
--END FFMPEG ERROR--
```

I'm just wondering what are the reasons for this timeout? We only convert some smaller clips, so it seems like the ffmpeg proccess is just hanging and doesn't give a response?

**Comment by njoyard** [comment]
I don't have enough info to tell what's happening here. If some ffmpeg processes hang around you should probably remove the timeout and add an other way of detecting long running processes, so that you can then check in live what's happening (is ffmpeg still running, has fluent-ffmpeg hanged, etc). Or if you have some code and/or input files that reproduce the problem systematically, post them here :)

**Comment by dnish** [comment]
We're using temp files and the error only occurs on certain conversions (in production). Most of the videos are small clips which were generated by the users, so we have to deal with different formats like mp4 or webm. 

I'll try to hold the temporary files and check if we can reproduce the error on our dev machine.

**Comment by Kostanos** [comment]
In my case a got this every 30 seconds:
```
camera.on('error', (err, stdout, stderr) => {
  console.log(err.message);
  console.log(stderr);
}
# produces the following output every 30 seconds:
process ran into a timeout (30s)
[h264 @ 0x55f2a9819a80] error while decoding MB 33 12, bytestream -15
[h264 @ 0x55f2a9819a80] cabac decode of qscale diff failed at 117 12
[h264 @ 0x55f2a9819a80] error while decoding MB 117 12, bytestream 212963
```
Any idea? what other info do you need, to be able to identify the source of the error?

**Comment by Kostanos** [comment]
I found the problem here. I expected to use the option `timeout` in 
```
self.camera = FFMpeg(cameraUrl, {timeout: 30});
```
for timeout in case if the camera is not reachable. But it actually the timeout general.

I'm trying now the different approach:
```
self.camera = FFMpeg(cameraUrl);
self.camera.inputOptions(['-stimeout 30', '-loglevel error'])
...
```
Now I don't have the timeout every 30 seconds. But still need to test the situation when camera actually is not reachable.

**Comment by njoyard** [comment]
Closing as no more info was provided by OP.

@Kostanos please open a separate issue if needed.
