### ISSUE TITLE
Adding album art to mp3 file

### ISSUE THREAD

**Issue by trustedtomato** [fluent-ffmpeg/node-fluent-ffmpeg#705]
### Version information

* fluent-ffmpeg version: 2.1.0
* ffmpeg version: 2.8.11-0ubuntu0.16.04.1
* OS: Ubuntu xenial

### Code to reproduce

```js
const proc = new ffmpeg('test.mp4');
proc.addOutputOption('-i','test.png')
proc.addOutputOption('-map','0:0')
proc.addOutputOption('-map','1:0')
proc.addOutputOption('-c','copy')
proc.addOutputOption('-id3v2_version','3')
proc.saveToFile('test.mp3');
```

### Expected results
test.mp3 with test.png as album art

### Observed results
```Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument```

**Comment by FireController1847** [comment]
Have you gotten this to work?

**Comment by trustedtomato** [comment]
Nope. I had to use browser-id3-writer.
Its pretty decent, but I would still love to see the ffmpeg solution.

**Comment by FireController1847** [comment]
I actually got it to work using this exact implementation. Basically, I've made a YouTube Playlist Downloader for music. Instead of putting the options in when I downloaded the stream (which resulted in a 1 second long file with a black album cover), I added it to a separate function AFTER my initial download was complete to add the metadata. Then, I saved it as a different filename, unlinked it, and renamed the new file back to the old file. Hallelujah. It worked! When I get home later today I'll send my example code :)

**Comment by FireController1847** [comment]
Here's that code example I promised.
```js
const albumCover = 'cover.png';
const path = 'mysongpath.mp3';
const tempPath = 'mysongpath.temp.mp3';
const strm = ffmpeg(path).addOutputOptions('-i', albumCover, '-map', '0:0', '-map', '1:0', '-c', 'copy', '-id3v2_version', '3').save(tempPath);
strm.on('end', () => {
  fs.unlinkSync(path);
  fs.renameSync(tempPath, path);
  resolve();
});
```

**Comment by njoyard** [comment]
Guys, if you intend to use fluent-ffmpeg to pass a raw list of options, just call spawn directly instead....
