### ISSUE TITLE
got ffmpeg exited with code 1 with special mp4 file  while using readstream as input

### ISSUE THREAD

**Issue by Esimorp** [fluent-ffmpeg/node-fluent-ffmpeg#823]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version:   
ffmpeg version N-91282-gc5e6c0b5f6 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 18.102 / 56. 18.102
libavcodec     58. 20.101 / 58. 20.101
libavformat    58. 17.100 / 58. 17.100
libavdevice    58.  4.101 / 58.  4.101
libavfilter     7. 25.100 /  7. 25.100
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
libpostproc    55.  2.100 / 55.  2.100
* OS: windows 10 17134
#### code 1
```js
const fs = require("fs");
ffmpeg = require('fluent-ffmpeg');
let file = '../testFileResource/t.mp4';
let infs = fs.createReadStream(file);
let proc = ffmpeg(infs)
    .on('error', function (err) {
        console.log('an error happened: ' + err.message);
    })
    .save('f.mp4');

```
#### code 2
```js
const fs = require("fs");
ffmpeg = require('fluent-ffmpeg');
let file = '../testFileResource/t.mp4';
let infs = fs.createReadStream(file);
let proc = ffmpeg(file)
    .on('error', function (err) {
        console.log('an error happened: ' + err.message);
    })
    .save('f.mp4');

```
(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
code 2 work very well
but with code 1 I got the follow result

an error happened: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input
Cannot determine format of input stream 0:1 after EOF
Error marking filters as finished
Conversion failed!

now i have no idea why it happens like that

**Comment by stajics** [comment]
Did you manage to solve this somehow?

**Comment by llcat** [comment]
Hi, this problem is caused by `moov atom` metadata is on the end of the mp4 file, 
so if you want get stream of it, you should move the `moov atom` to the head of the file.

**how to solve it?**
1.  check the file is Streamable?
use `mediainfo` tool to check the info about your mp4 file
you may see`"IsStreamable": "No",`.

2. use `ffmpeg` tool to convert the unstreamable file to a streamable file
`ffmpeg -i no_streamable.mp4 -movflags faststart -f mp4 -y streamable.mp4`
then you can you the converted file, this time will not throw ffmpeg exited with code 1: pipe:0: Invalid data found when processing input

3. can I use the options `movflags` in fluent-ffmpeg?
Unfortunately, you can't, there exists some bugs for it
```js
let inputStream = fs.createReadStream("no_streamable.mp4")
ffmpeg(inputStream)
    .inputOptions("-movflags faststart")
    .output("streamable.mp4")
    .format("mp4")
    .on("start", (cmd)=>{
        console.log("--- ffmpeg start process ---")
        console.log(`cmd: ${cmd}`)
    })
    .on("end",()=>{
        console.log("--- end processing ---")
    })
    .on("error", (err)=>{
        console.log("--- ffmpeg meets error ---")
        console.log(err)
    })
    .run()
```
you will get a error: ffmpeg exited with code 1: Option movflags not found.

because the generate cmd is like that: `ffmpeg -movflags faststart -i pipe:0 -y -f mp4 streamable.mp4`
you can try step2 cmd like this, it will throw the same error, it seems that the ffmpeg can't understand the cmd format.
`ffmpeg -movflags faststart -i no_streamable.mp4 -f mp4 -y streamable.mp4`
i don't know how to fix it too~ sadly

@Esimorp 
@stajics

**Comment by llcat** [comment]
oh, i forgot to attach some link for reference
> [what-is-the-difference-between-these-2-videos](https://stackoverflow.com/questions/52689718/what-is-the-difference-between-these-2-videos)
[post-processing-in-ffmpeg-to-move-moov-atom-in-mp4-files-qt-faststar](https://stackoverflow.com/questions/8061798/post-processing-in-ffmpeg-to-move-moov-atom-in-mp4-files-qt-faststart)
[mov_002c-mp4_002c-ismv](https://ffmpeg.org/ffmpeg-formats.html#mov_002c-mp4_002c-ismv)

**Comment by llcat** [comment]
> oh, i forgot to attach some link for reference
> 
> > [what-is-the-difference-between-these-2-videos](https://stackoverflow.com/questions/52689718/what-is-the-difference-between-these-2-videos)
> > [post-processing-in-ffmpeg-to-move-moov-atom-in-mp4-files-qt-faststar](https://stackoverflow.com/questions/8061798/post-processing-in-ffmpeg-to-move-moov-atom-in-mp4-files-qt-faststart)
> > [mov_002c-mp4_002c-ismv](https://ffmpeg.org/ffmpeg-formats.html#mov_002c-mp4_002c-ismv)

i made a mistake with the code in step 3:
it should use `outputOptions("-movflags faststart")`,
but this option just work well with file url input, if you pass a stream to input, it's no useful

**Comment by minhzc** [comment]
Here is the moveflags command we need, hope you all solve your problems:
ffmpeg -i original.mp4 -movflags faststart -acodec copy -vcodec copy original_streamable.mp4

**Comment by MichaelMikeJones** [comment]
@llcat Hi, thank you for solutions. Is the bug fixed? I still get them in  2021, it is two years later. Is it possible to get `isStreamable` using `ffprobe` instead of `mediainfo`?

**Comment by sw360cab** [comment]
@MichaelMikeJones I think that this issue is not solvable whether video has information written at the end of the stream. 
It could be interesting trying to read stream from the end, but I don't know if it is doable without downloading the whole file.

The only fix is to download the whole file and process a file instead of a stream or to ensure you work with files having the headers `-movflags faststart' set.

**Comment by yogesh1012-lgtm** [comment]
Exception: ffmpeg exited with code 1. See console for details
