### ISSUE TITLE
Usage of ffmpeg cli switches instead of fluent interface

### ISSUE THREAD

**Issue by straussCS** [fluent-ffmpeg/node-fluent-ffmpeg#909]
We receive ffmpeg command line switches from a server like .e.g. 
`-s 1920x1080 -movflags faststart -r 25 -c:v libx264 -preset superfast -b:v 4000k -minrate 3000k -maxrate 5000k -bufsize 13000k -pix_fmt yuv420p -c:a aac -b:a 128k -avoid_negative_ts 1`

Is it possible to convert such a string to a node-fluentf-fmpeg command or pass it directly to the ffmpeg binary?

### Version information

* fluent-ffmpeg version: latest
* ffmpeg version: latest
* OS: all

**Comment by orangecms** [comment]
You could just split them up and push them into an array. See https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#outputoptionsoption-add-custom-output-options :)

Otherwise you can use the [Node.js child process API](https://nodejs.org/api/child_process.html). Just be aware that you need to sanitize the arguments to not end up with RCE.
