### ISSUE TITLE
Question: Capture Webcam / dshow Input

### ISSUE THREAD

**Issue by HeyWrecker** [fluent-ffmpeg/node-fluent-ffmpeg#99]
In the examples, every case given is with a static file. Is there any way to feed in a "dshow" source into node-fluent-ffmpeg and use it to kick off a live streaming session?

**Comment by citosid** [comment]
@HeyWrecker were you able to do it?

**Comment by HeyWrecker** [comment]
Yes. I did find a way to pass in the 'q' command and then call the process.exit() method. You can view it here:

https://github.com/HeyWrecker/LiveFFMPEG/blob/master/module.js

**Comment by njoyard** [comment]
@citosid I think the answers I posted above are a better solution to what @HeyWrecker did (my 2 cents). If it still does not meet your needs, please tell me !

**Comment by citosid** [comment]
Yes, @njoyard. Actually this is how I'm doing it:

```javascript
app.locals._ffmpeg = {commands: {}};
var Event = function() {
    this.cmd = app.locals._ffmpeg[_id] = ffmpeg(!input && video ? path.normalize(video) : input, _conf);
}
Event.getInfo = function(_id) {
    return app.locals._ffmpeg[_id] && app.locals._ffmpeg[_id]._data ? app.locals._ffmpeg[_id]._data : null;
};
Event.stop= function(_id) {
    if (app.locals._ffmpeg[_id])
        app.locals._ffmpeg[_id].kill();
};
```
What do you think?

**Comment by Arrow7000** [comment]
I'm currently trying to do the same thing, namely stream video from a webcam into a file. 

However I only want the process to stop when triggered to do so by an event in my JS file, because I want to have a streaming recording window 3 mins long. Everything past 3 mins gets deleted unless I explicitly want to save a particular clip, which i will handle separately. 

What would the best way of doing this be? I have to be honest, I can't make sense of the previously posted code snippets, so any guidance would be appreciated!

**Comment by Arrow7000** [comment]
If it helps, I managed to get video from ffmpeg by this command `ffmpeg -f dshow -i video="HD USB Camera" output.avi`. However I couldn't get any combination of options to work with this module.
